---
--- Generated by EmmyLua(https://github.com/EmmyLua)
--- Created by onelei.
--- DateTime: 2020/9/6 20:03
---

UIMgr = {}

local unity_uiMgr_instance = CS.Lemon.UIMgr.Instance

function UIMgr.Init()
    ---unity_uiMgr_instance:Init()
end

function UIMgr.Open(ui_type,ui_data)
    ---unity_uiMgr_instance:Open(ui_type,ui_data)
end

function UIMgr.Close(ui_type)
    ---unity_uiMgr_instance:Close(ui_type)
end

return UIMgr