---
--- Generated by EmmyLua(https://github.com/EmmyLua)
--- Created by onelei.
--- DateTime: 2020/9/6 20:09
---

---@class UIType

UIType =
{
    None = "None",
    UILogin = "UILogin",
    UICity = "UICity",
    UIBattle = "UIBattle",
    UITest1 = "UITest1",
    UITest2 = "UITest2",
}

return UIType