---
--- Generated by EmmyLua(https://github.com/EmmyLua)
--- Created by onelei.
--- DateTime: 2020/8/23 16:36
---

local StageActionMgr = {}

function StageActionMgr:Init()

    self.Cfg = {}
    self.Cfg[StageUtility.EStage.TEST1] = "Common.StageAction.StageActionTest1"
    self.Cfg[StageUtility.EStage.TEST2] = "Common.StageAction.StageActionTest2"

    self.ActionGroup = {}
end

function StageActionMgr:Clear()

end

function StageActionMgr:Enter()

end

function StageActionMgr:Exit()

end

function StageActionMgr:GetOrAddAction(eStage)
    local stageAction = self.ActionGroup[eStage]
    if not stageAction then
        local stageFilePath = self.Cfg[eStage]
        local stageActionFile = require(stageFilePath)
        stageAction = stageActionFile.new()
        self.ActionGroup[eStage] = stageAction
    end
    return stageAction
end

function StageActionMgr:RemoveAction(eStage)
    local stageAction = self.ActionGroup[eStage]
    if not stageAction then
        return
    end
    LuaUtil.UnLoad(self.Cfg[eStage])
    self.ActionGroup[eStage] = nil
end

return StageActionMgr