---
--- Generated by EmmyLua(https://github.com/EmmyLua)
--- Created by onelei.
--- DateTime: 2020/8/2 11:06
---

UIMain = class("UIMain",UIBase)

function UIMain:Open()

end

function UIMain:Close()

end