---
--- Generated by EmmyLua(https://github.com/EmmyLua)
--- Created by onelei.
--- DateTime: 2020/8/23 16:34
---

local StageActionBase = class("StageActionBase")

function StageActionBase:ctor()

end

function StageActionBase:OnEnter()

end

function StageActionBase:OnExit()

end

return StageActionBase