---
--- Generated by EmmyLua(https://github.com/EmmyLua)
--- Created by onelei.
--- DateTime: 2020/8/23 16:33
---

---@class StageUtility

StageUtility = {}

StageUtility.EStage =
{
    NONE = 0,
    TEST1 = 1,
    TEST2 = 2,
}

function StageUtility.Init()

end

function StageUtility.Enter()

end

function StageUtility.Exit()

end

return StageUtility