---
--- Generated by EmmyLua(https://github.com/EmmyLua)
--- Created by onelei.
--- DateTime: 2020/8/2 11:01
---

---@class LuaInit

--package.cpath = package.cpath .. ';C:/Users/ahlei/AppData/Roaming/JetBrains/IdeaIC2020.1/plugins/intellij-emmylua/classes/debugger/emmy/windows/x64/?.dll'
--local dbg = require('emmy_core')
--dbg.tcpListen('localhost', 9966)

LuaInit = {}

require("Function")
require("Common.LuaUtil")
require("Common.Debug")
require("Common.LuaDef")
require("Common.EventMgr")

require("GameStage.GameStageUtility")



return LuaInit