---
--- Generated by EmmyLua(https://github.com/EmmyLua)
--- Created by onelei.
--- DateTime: 2020/8/2 16:01
---

UIBase = class("UIBase")

function UIBase:ctor()
    Debug.Log("ctor")
end

function UIBase:Open()

end

function UIBase:Close()

end

