---
--- Generated by EmmyLua(https://github.com/EmmyLua)
--- Created by onelei.
--- DateTime: 2020/8/8 22:57
---
---* Action Node
---* 它完成具体的一次(或一个step)的行为，视需求返回值
---* 叶子节点

---@class BTNodeAction
local BTNode = require("Common.BT.BTNode")
local BTNodeAction = class("BTNodeAction",BTNode)

function BTNodeAction:ctor(Opts)
    BTNode.ctor(self,Opts)
end

function BTNodeAction:DoAction()
    return LuaDef.BTResult.NONE
end

return BTNodeAction