---
--- Generated by EmmyLua(https://github.com/EmmyLua)
--- Created by onelei.
--- DateTime: 2020/8/22 14:40
---
---* ParallelSequence Node
---* 并发执行它的所有Child Node
---* 而向Parent Node返回的值和Parallel Node所采取的具体策略相关
---* Parallel Sequence Node:一True则返回True,全False才返回False

---@class BTNodeParallelSequence
local BTParallel = require("Common.BT.BTNodeParallel")
local BTNodeParallelSequence = class("BTNodeParallelSequence",BTParallel)

function BTNodeParallelSequence:ctor(Opts)
    BTParallel.ctor(self,Opts)
    self:Reset()
end

function BTNodeParallelSequence:DoAction()
    if self.Children == nil or #self.Children == 0 then
        return LuaDef.BTResult.SUCCESSFUL
    end

    local result
    local childCount = #self.Children
    for i = 1, childCount do
        local action = self.Children[i]
        if action then
            result =  action:DoAction()
            if result == LuaDef.BTResult.SUCCESSFUL then
                self.__bSuccess = true
            end
            if result == LuaDef.BTResult.RUNNING then
                table.insert(self.__WaitNodes,#self.__WaitNodes,action)
            end
        end
    end

    if #self.__WaitNodes > 0 then
        return LuaDef.BTResult.RUNNING
    end

    if self.__bSuccess then
        result = LuaDef.BTResult.SUCCESSFUL
    else
        result = LuaDef.BTResult.FAIL
    end

    self:Reset()

    return result
end


function BTNodeParallelSequence:Reset()
    self.__WaitNodes = {}
    self.__bSuccess = false
end

return BTNodeParallelSequence