---
--- Generated by EmmyLua(https://github.com/EmmyLua)
--- Created by onelei.
--- DateTime: 2020/8/22 15:29
---

---@class StepActionBase
local BTNode = require("Common.BT.BTNode")
local StepActionBase = class("StepActionBase",BTNode)

function StepActionBase:SetOpts(...)
    self.Opts = { ... }
end

function StepActionBase:DoAction()

end

return StepActionBase