---
--- Generated by EmmyLua(https://github.com/EmmyLua)
--- Created by onelei.
--- DateTime: 2020/8/22 15:36
---

---@class StepActionTest2
local StepActionBase = class("Common.StepAction.StepActionBase")
local StepActionTest2 = class("StepActionTest2",StepActionBase)

function StepActionTest2:SetOpts(...)
    Debug.Log("Opts: ",...)
    self.Opts = { ... }
    self.time = 0
end

function StepActionTest2:DoAction()
    self.time = self.time + 1
    Debug.Log("StepActionTest2: ",self.time)
    if self.time < 5 then
        return LuaDef.BTResult.RUNNING
    end
    return LuaDef.BTResult.SUCCESSFUL
end

return StepActionTest2