---
--- Generated by EmmyLua(https://github.com/EmmyLua)
--- Created by onelei.
--- DateTime: 2020/8/22 15:32
---

StepUtility = {}

StepUtility.EAction =
{
    NONE = 0,
    TEST1 = 1,
    TEST2 = 2,
}

local StepActionMgr
local FilePath
function StepUtility.Init()
    FilePath = {}
    FilePath[1] = "Common.StepAction.StepActionMgr"
    StepActionMgr = require(FilePath[1])
    StepActionMgr:Init()
end

function StepUtility.Clear()
    for i, v in pairs(FilePath) do
        LuaUtil.UnLoad(v)
    end
end

function StepUtility.Append(action_type,...)
    StepActionMgr:Append(action_type,...)
end

function StepUtility.Remove(action)
    StepActionMgr:Remove(action)
end

function StepUtility.Update()
    StepActionMgr:Update()
end

StepUtility.Init()

return StepUtility