---
--- Generated by EmmyLua(https://github.com/EmmyLua)
--- Created by onelei.
--- DateTime: 2020/9/6 21:48
---

Res = {}

function Res.LoadPrefab(name,path)

end

function Res.LoadImage(name,path)

end

function Res.UnLoad(name)

end

return Res