---
--- Generated by EmmyLua(https://github.com/EmmyLua)
--- Created by onelei.
--- DateTime: 2020/8/8 23:18
---
---* BTNodeDecoration
---* 装饰节点

---@class BTNodeDecoration

local BTNode = require("Common.BT.BTNode")
local BTNodeDecoration = class("BTNodeDecoration",BTNode)

return BTNodeDecoration