---
--- Generated by EmmyLua(https://github.com/EmmyLua)
--- Created by onelei.
--- DateTime: 2020/8/8 23:15
---
---* Condition node.
---* 条件节点

---@class BTNodeCondition
local BTNode = require("Common.BT.BTNode")
local BTNodeCondition = class("BTNodeCondition",BTNode)

function BTNodeCondition:ctor(Opts)
    BTNode.ctor(self,Opts)
end

function BTNodeCondition:DoAction()
    if self.Opts.Condition ~= nil and self.Opts.Condition(nil,self.Opts.BlackBoard) then
        return LuaDef.BTResult.SUCCESSFUL
    end
    return LuaDef.BTResult.FAIL
end

return BTNodeCondition