---
--- Generated by EmmyLua(https://github.com/EmmyLua)
--- Created by onelei.
--- DateTime: 2020/8/22 15:28
---

---@class StepActionMgr

local StepActionMgr = {}

function StepActionMgr:Init()
    if self.bInit == true then
        return
    end
    self.bInit = true
    self.__Action_Pool = {}
    self.__CacheAction_Pool = {}

    self.Cfg = {}
    self.Cfg[StepUtility.EAction.TEST1] = "Common.StepAction.StepActionTest1"
    self.Cfg[StepUtility.EAction.TEST2] = "Common.StepAction.StepActionTest2"


    local StepActionSequence = require("Common.StepAction.StepActionSequence")
    self.Sequence = StepActionSequence.new()
end

function StepActionMgr:Clear()
    self.__Action_Pool = nil
end

function StepActionMgr:GetOrAddAction(action_type,...)
   local action = self.__Action_Pool[action_type]
    if not action then
        local actionFilePath = self.Cfg[action_type]
        if not actionFilePath then
            Debug.LogError("cane not find action_type = ",action_type)
            return nil
        end
        local file = require(actionFilePath)
        action = file.new()
        self.__CacheAction_Pool[action_type] = action
        self.__Action_Pool[action_type] = action
    end
    action:SetOpts(...)
    return action
end

function StepActionMgr:Append(action_type,...)
    ---设置参数
    local action = self:GetOrAddAction(action_type,...)
    self.Sequence:Add(action)
end

function StepActionMgr:Update()
    self.Sequence:DoAction()
end


return StepActionMgr