---
--- Generated by EmmyLua(https://github.com/EmmyLua)
--- Created by onelei.
--- DateTime: 2020/9/6 20:14
---

---@class GameStageHotUpdate

local GameStageBase = require("GameStage.GameStageBase")
local GameStageHotUpdate = class("GameStageHotUpdate",GameStageBase)

function GameStageHotUpdate:OnEnter()
    GameStageBase.OnEnter(self)
end

function GameStageHotUpdate:OnExit()
    GameStageBase.OnExit(self)
end

return GameStageHotUpdate