---
--- Generated by EmmyLua(https://github.com/EmmyLua)
--- Created by onelei.
--- DateTime: 2020/9/6 20:14
---

---@class GameStageBase

local GameStageBase = class("GameStageBase")

function GameStageBase:ctor()

end

function GameStageBase:OnEnter()

end

function GameStageBase:OnExit()

end

return GameStageBase