---
--- Generated by EmmyLua(https://github.com/EmmyLua)
--- Created by onelei.
--- DateTime: 2020/8/2 10:47
---

---@class Debug

Debug = {}

local  __Debug = CS.UnityEngine.Debug

function Debug.Log(...)
    local message = LuaUtil.Concat(...)
    __Debug.Log(message)
end

function Debug.LogWarning(...)
    local message = LuaUtil.Concat(...)
    __Debug.LogWarning(message)
end

function Debug.LogError(...)
    local message = LuaUtil.Concat(...)
    __Debug.LogError(message)
end

return Debug