---
--- Generated by EmmyLua(https://github.com/EmmyLua)
--- Created by onelei.
--- DateTime: 2020/8/2 11:01
---

---@class EventMgr

EventMgr = {}

local __Event_Pool

function EventMgr.Init()
    __Event_Pool = {}
end

function EventMgr.AddListener(target,key,func)
    if not __Event_Pool[key] then
        local __Target_Pool = {}
        __Event_Pool[key] = __Target_Pool
    end

    local __Target_Pool = __Event_Pool[key].__Target_Pool
    if not __Target_Pool[target] then
        local __Key_Pool = __Target_Pool[target].__Key_Pool
        if not __Key_Pool then
            __Key_Pool = {}
        end

        if __Key_Pool[key] then
            Debug.LogError(key," key already add.")
            return
        end
        __Key_Pool[key] = func
    end
end

function EventMgr.RemoveListener(target,key,func)
    if __Event_Pool[key] then
        local __Target_Pool = __Event_Pool[key].__Target_Pool
        if __Target_Pool and __Target_Pool[target] then
            local __Key_Pool = __Target_Pool[target].__Key_Pool
            if __Key_Pool and __Key_Pool[key] then
                __Key_Pool[key] = nil
            end
        end
    end
end

function EventMgr.RemoveListenerByTarget(target)
    for i, v in pairs(__Event_Pool) do
        if v and v[target] then
            v[target] = nil
        end
    end
end

function EventMgr.Send(key,...)
    if __Event_Pool[key] then
        local __Target_Pool = __Event_Pool[key].__Target_Pool
        for i, v in pairs(__Target_Pool) do
            local __Key_Pool = v.__Key_Pool
            if __Key_Pool and __Key_Pool[key] and __Key_Pool[key].func then
                __Key_Pool[key].func(...)
            end
        end
    end
end

EventMgr.Init()

return EventMgr