---
--- Generated by EmmyLua(https://github.com/EmmyLua)
--- Created by onelei.
--- DateTime: 2020/9/6 20:14
---

---@class GameStageLogin

local GameStageBase = require("GameStage.GameStageBase")
local GameStageLogin = class("GameStageLogin",GameStageBase)

function GameStageLogin:OnEnter()
    GameStageBase.OnEnter(self)

    ---打开Login界面
    UIMgr.Open(UIType.UILogin)

end

function GameStageLogin:OnExit()
    GameStageBase.OnExit(self)
end

return GameStageLogin