---
--- Generated by EmmyLua(https://github.com/EmmyLua)
--- Created by onelei.
--- DateTime: 2020/9/6 20:14
---

---@class GameStageBattle

local GameStageBase = require("GameStage.GameStageBase")
local GameStageBattle = class("GameStageBattle",GameStageBase)

function GameStageBattle:OnEnter()
    GameStageBase.OnEnter(self)
end

function GameStageBattle:OnExit()
    GameStageBase.OnExit(self)
end

return GameStageBattle