---
--- Generated by EmmyLua(https://github.com/EmmyLua)
--- Created by onelei.
--- DateTime: 2020/9/6 20:14
---

---@class GameStageCity

local GameStageBase = require("GameStage.GameStageBase")
local GameStageCity = class("GameStageCity",GameStageBase)

function GameStageCity:OnEnter()
    GameStageBase.OnEnter(self)
end

function GameStageCity:OnExit()
    GameStageBase.OnExit(self)
end

return GameStageCity